export const income_data = [
  { Owner: 'Self', IncomeSource: 'Main Job' },
  { Owner: 'Partner', IncomeSource: 'Main Job' },
  { Owner: 'Self', IncomeSource: 'Side Job' },
  { Owner: 'Partner', IncomeSource: 'Side Job' },
  { Owner: 'Self', IncomeSource: 'Interest/Dividends' },
  { Owner: 'Partner', IncomeSource: 'Interest/Dividends' },
  { Owner: 'Self', IncomeSource: 'Child Support' },
  { Owner: 'Partner', IncomeSource: 'Child Support' },
  { Owner: 'Self', IncomeSource: 'Bonus' },
  { Owner: 'Partner', IncomeSource: 'Bonus' },
  { Owner: 'Self', IncomeSource: 'Rental Income' },
  { Owner: 'Partner', IncomeSource: 'Rental Income' },
  { Owner: 'Self', IncomeSource: 'Other' },
  { Owner: 'Partner', IncomeSource: 'Other' },
  { Owner: 'Self', IncomeSource: 'Other' },
  { Owner: 'Partner', IncomeSource: 'Other' },
  { Owner: 'Self', IncomeSource: 'Other' },
  { Owner: 'Partner', IncomeSource: 'Other' },
  { Owner: 'Self', IncomeSource: 'Other' },
  { Owner: 'Partner', IncomeSource: 'Other' },
];

export const savings_data = [
  { Owner: 'Self', Description: '6 mo. Emergency Fund Savings Acct' },
  { Owner: 'Partner', Description: '6 mo. Emergency Fund Savings Acct' },
  { Owner: 'Self', Description: "Add'l Savings Acct #1" },
  { Owner: 'Partner', Description: "Add'l Savings Acct #2" },
  { Owner: 'Joint', Description: "Add'l Savings Acct #3" },
  { Owner: 'Self', Description: "Add'l Savings Acct #4" },
  { Owner: 'Self', Description: 'Investment Account #1' },
  { Owner: 'Partner', Description: 'Investment Account #2' },
  { Owner: 'Joint', Description: 'Investment Account #3' },
  { Owner: 'Self', Description: '529 Plan: Education Investment Account' },
  { Owner: 'Self', Description: 'Saving for a Home (transfer to a sav acct)' },
  { Owner: 'Self', Description: 'Saving for a Vacation (transfer to a sav acct)' },
  { Owner: 'Self', Description: 'Saving for a Vehicle (transfer to a sav acct)' },
  { Owner: 'Self', Description: 'Saving for Misc. (transfer to a sav acct)' },
  { Owner: 'Partner', Description: 'Saving for Misc. (transfer to a sav acct)' },
  { Owner: 'Self', Description: 'Tax Return Refund (deposit to a sav acct)' },
  { Owner: 'Self', Description: 'Extra Paychecks allocated to Savings (deposit to a sav acct)' },
];

export const retirements_data = [
  { Owner: 'Self', Description: 'Retirement (401k, 401KRoth) Payroll Deduction' },
  { Owner: 'Partner', Description: 'Retirement (401k, 401KRoth) Payroll Deduction' },
  { Owner: 'Self', Description: 'Retirement (401k, 401KRoth) Prior Job' },
  { Owner: 'Partner', Description: 'Retirement (401k, 401KRoth) Prior Job' },
  { Owner: 'Self', Description: 'IRA' },
  { Owner: 'Partner', Description: 'IRA' },
  { Owner: 'Self', Description: 'IRA' },
  { Owner: 'Self', Description: 'ROTH' },
  { Owner: 'Partner', Description: 'ROTH' },
  { Owner: 'Self', Description: 'ROTH' },
  { Owner: 'Self', Description: 'Spousal IRA (if file MFJ)' },
  { Owner: 'Partner', Description: 'Spousal IRA (if file MFJ)' },
];

export const debt_data = [
  { Owner: 'Self', description: 'Credit Card #1 Payment' },
  { Owner: 'Self', description: 'Credit Card #2 Payment' },
  { Owner: 'Self', description: 'Credit Card #3 Payment' },
  { Owner: 'Self', description: 'Credit Card #4 Payment' },
  { Owner: 'Self', description: 'Credit Card #5 Payment' },
  { Owner: 'Self', description: 'Credit Card #6 Payment' },
  { Owner: 'Self', description: 'Credit Card #7 Payment' },
  { Owner: 'Self', description: 'Credit Card #8 Payment' },
  { Owner: 'Self', description: 'Credit Card #9 Payment' },
  { Owner: 'Self', description: 'Credit Card #10 Payment' },
  { Owner: 'Self', description: 'Department Store Card #1' },
  { Owner: 'Self', description: 'Department Store Card #2' },
  { Owner: 'Self', description: 'Department Store Card #3' },
  { Owner: 'Self', description: 'Department Store Card #4' },
  { Owner: 'Self', description: 'Department Store Card #5' },
  { Owner: 'Self', description: 'Department Store Card #6' },
  { Owner: 'Self', description: 'Department Store Card #7' },
  { Owner: 'Self', description: 'Family/Friend Loan Payment ' },
  { Owner: 'Partner', description: 'Family/Friend Loan Payment ' },
  { Owner: 'Self', description: "Income Tax Lien/Payment Due (Consider making add'l tax withholdings to avoid/minimize a tax bill)" },
  { Owner: 'Self', description: 'Medical Debt' },
  { Owner: 'Self', description: 'Personal Loan Payment' },
  { Owner: 'Partner', description: 'Personal Loan Payment' },
  { Owner: 'Self', description: 'Student Loans' },
  { Owner: 'Partner', description: 'Student Loans' },
  { Owner: 'Joint', description: 'Student Loans' },
  { Owner: 'Self', description: 'Student Loans' },
  { Owner: 'Self', description: 'Other' },
  { Owner: 'Partner', description: 'Other' },
  { Owner: 'Joint', description: 'Other' },
  { Owner: 'Self', description: 'Other' },
  { Owner: 'Partner', description: 'Other' },
  { Owner: 'Joint', description: 'Other' },
  { Owner: 'Self', description: '' },
  { Owner: 'Partner', description: '' },
  { Owner: 'Joint', description: '' },
  { Owner: 'Self', description: '' },
  { Owner: 'Partner', description: '' },
];

export const expenses_data = [
  { Owner: 'Self', Category: 'Housing', Description: 'Rent' },
  { Owner: 'Self', Category: 'Housing', Description: 'Mortgage/House Payment' },
  { Owner: 'Self', Category: 'Housing', Description: 'Home Equity Line of Credit' },
  { Owner: 'Self', Category: 'Housing', Description: 'Cable TV / Streaming Services' },
  { Owner: 'Self', Category: 'Housing', Description: 'Electricity/Gas/Propane' },
  { Owner: 'Self', Category: 'Housing', Description: 'Garbage' },
  { Owner: 'Self', Category: 'Housing', Description: 'Gardener' },
  { Owner: 'Self', Category: 'Housing', Description: 'HO Insurance' },
  { Owner: 'Self', Category: 'Housing', Description: 'Home Improvement (Consider using a portion of/or all extra paychecks)' },
  { Owner: 'Self', Category: 'Housing', Description: 'Home Repairs & Maintenance (Consider using a portion of/or all extra paychecks)' },
  { Owner: 'Self', Category: 'Housing', Description: 'Home Security' },
  { Owner: 'Self', Category: 'Housing', Description: 'Homeowner Dues #1' },
  { Owner: 'Self', Category: 'Housing', Description: 'Homeowner Dues #2' },
  { Owner: 'Self', Category: 'Housing', Description: 'Housecleaning service' },
  { Owner: 'Self', Category: 'Housing', Description: 'Pool Service' },
  { Owner: 'Self', Category: 'Housing', Description: 'Property Taxes' },
  { Owner: 'Self', Category: 'Housing', Description: 'Sewer' },
  { Owner: 'Self', Category: 'Housing', Description: 'Water' },
  { Owner: 'Self', Category: 'Housing', Description: 'Wi-fi / Internet' },
  { Owner: 'Self', Category: 'Housing', Description: 'Yard/Garden Supplies' },
  { Owner: 'Self', Category: 'Housing', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Housing', Description: 'Enter' },
  { Owner: 'Joint', Category: 'Housing', Description: 'Enter' },
  { Owner: 'Self', Category: 'Housing', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Housing', Description: 'Enter' },
  { Owner: 'Joint', Category: 'Housing', Description: 'Enter' },
  { Owner: 'Self', Category: 'Housing', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Housing', Description: 'Enter' },
  { Owner: 'Self', Category: 'Transportation', Description: 'Car Payment #1' },
  { Owner: 'Self', Category: 'Transportation', Description: 'Car Payment #2' },
  { Owner: 'Self', Category: 'Transportation', Description: 'Car Payment #3' },
  { Owner: 'Self', Category: 'Transportation', Description: 'Car Wash/Detailing Service' },
  { Owner: 'Self', Category: 'Transportation', Description: 'Gas /fuel' },
  { Owner: 'Self', Category: 'Transportation', Description: 'Lease Payment #1' },
  { Owner: 'Self', Category: 'Transportation', Description: 'Lease Payment #2' },
  { Owner: 'Self', Category: 'Transportation', Description: 'Motorcycle Payment' },
  { Owner: 'Self', Category: 'Transportation', Description: 'Parking' },
  { Owner: 'Self', Category: 'Transportation', Description: 'Public transportation (Bart, Bus, Cal Train)' },
  { Owner: 'Self', Category: 'Transportation', Description: 'Repairs & Maintenance' },
  { Owner: 'Self', Category: 'Transportation', Description: 'Vehicle Insurance' },
  { Owner: 'Self', Category: 'Transportation', Description: 'Vehicle Registration Fees (DMV)' },
  { Owner: 'Partner', Category: 'Transportation', Description: 'Vehicle Registration Fees (DMV)' },
  { Owner: 'Joint', Category: 'Transportation', Description: 'Vehicle Registration Fees (DMV)' },
  { Owner: 'Self', Category: 'Transportation', Description: 'Vehicle Registration Fees (DMV)' },
  { Owner: 'Self', Category: 'Transportation', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Transportation', Description: 'Enter' },
  { Owner: 'Joint', Category: 'Transportation', Description: 'Enter' },
  { Owner: 'Self', Category: 'Charity', Description: 'Charities #1' },
  { Owner: 'Self', Category: 'Charity', Description: 'Charities #2' },
  { Owner: 'Self', Category: 'Charity', Description: 'Charities #3' },
  { Owner: 'Self', Category: 'Charity', Description: 'Charities #4' },
  { Owner: 'Self', Category: 'Charity', Description: 'Charities #5' },
  { Owner: 'Self', Category: 'Charity', Description: 'Religious Organizations' },
  { Owner: 'Self', Category: 'Charity', Description: 'Other' },
  { Owner: 'Self', Category: 'Charity', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Charity', Description: 'Enter' },
  { Owner: 'Joint', Category: 'Charity', Description: 'Enter' },
  { Owner: 'Self', Category: 'Food', Description: 'Cleaning Supplies' },
  { Owner: 'Self', Category: 'Food', Description: "Coffee houses (Starbucks, Peets, McDonald's)" },
  { Owner: 'Self', Category: 'Food', Description: 'Dining out' },
  { Owner: 'Self', Category: 'Food', Description: 'Food Services (Blue Apron)' },
  { Owner: 'Self', Category: 'Food', Description: 'Groceries' },
  { Owner: 'Self', Category: 'Food', Description: 'Toiletries' },
  { Owner: 'Self', Category: 'Food', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Food', Description: 'Enter' },
  { Owner: 'Joint', Category: 'Food', Description: 'Enter' },
  { Owner: 'Self', Category: 'Food', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Food', Description: 'Enter' },
  { Owner: 'Self', Category: 'Food', Description: 'Enter' },
  { Owner: 'Self', Category: 'Entertainment', Description: 'Concerts/clubs' },
  { Owner: 'Self', Category: 'Entertainment', Description: 'Date nights' },
  { Owner: 'Self', Category: 'Entertainment', Description: 'Host Holiday Parties: July 4th, Thanksgiving, Christmas, Other' },
  { Owner: 'Self', Category: 'Entertainment', Description: 'Movies/plays' },
  { Owner: 'Self', Category: 'Entertainment', Description: 'Parties: Other' },
  { Owner: 'Self', Category: 'Entertainment', Description: 'Professional Sporting events' },
  { Owner: 'Self', Category: 'Entertainment', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Entertainment', Description: 'Enter' },
  { Owner: 'Joint', Category: 'Entertainment', Description: 'Enter' },
  { Owner: 'Self', Category: 'Entertainment', Description: 'Enter' },
  { Owner: 'Self', Category: 'Children', Description: 'Adult Children Support' },
  { Owner: 'Self', Category: 'Children', Description: 'Allowance/spending money' },
  { Owner: 'Self', Category: 'Children', Description: 'Birthday Parties for Children' },
  { Owner: 'Self', Category: 'Children', Description: 'Child Care' },
  { Owner: 'Self', Category: 'Children', Description: 'Child Care Other (Babysitters)' },
  { Owner: 'Self', Category: 'Children', Description: 'Child Support' },
  { Owner: 'Self', Category: 'Children', Description: 'Clothes & Shoes' },
  { Owner: 'Self', Category: 'Children', Description: 'Computer & Accessories (keyboard & mouse, printer, Ink, Paper)' },
  { Owner: 'Self', Category: 'Children', Description: 'Diapers & Formula & baby food' },
  { Owner: 'Self', Category: 'Children', Description: 'Gifts for friends' },
  { Owner: 'Self', Category: 'Children', Description: 'Lessons (dance, karate, etc.)' },
  { Owner: 'Self', Category: 'Children', Description: 'Orthodontist' },
  { Owner: 'Self', Category: 'Children', Description: 'Preschool Tuition' },
  { Owner: 'Self', Category: 'Children', Description: 'Private School Tuition' },
  { Owner: 'Self', Category: 'Children', Description: 'School Books' },
  { Owner: 'Self', Category: 'Children', Description: 'School Money (Lunches)' },
  { Owner: 'Self', Category: 'Children', Description: 'Sports gear & equipment' },
  { Owner: 'Self', Category: 'Children', Description: 'Team dues' },
  { Owner: 'Self', Category: 'Children', Description: 'Toys/child gear' },
  { Owner: 'Self', Category: 'Children', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Children', Description: 'Enter' },
  { Owner: 'Joint', Category: 'Children', Description: 'Enter' },
  { Owner: 'Self', Category: 'Parent/Elder Care', Description: 'Parents Support' },
  { Owner: 'Partner', Category: 'Parent/Elder Care', Description: 'Parents Support' },
  { Owner: 'Joint', Category: 'Parent/Elder Care', Description: 'Parents Support' },
  { Owner: 'Self', Category: 'Pets/Animal', Description: 'Dog Walker' },
  { Owner: 'Self', Category: 'Pets/Animal', Description: 'Grooming' },
  { Owner: 'Self', Category: 'Pets/Animal', Description: 'Pet Food' },
  { Owner: 'Self', Category: 'Pets/Animal', Description: 'Pet Insurance' },
  { Owner: 'Self', Category: 'Pets/Animal', Description: 'Pet Meds' },
  { Owner: 'Self', Category: 'Pets/Animal', Description: 'Veterinarian visits' },
  { Owner: 'Self', Category: 'Pets/Animal', Description: 'Procedures not covered by insurance' },
  { Owner: 'Self', Category: 'Pets/Animal', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Pets/Animal', Description: 'Enter' },
  {
    Owner: 'Self',
    Category: 'Health Medicle',
    Description: 'Co-pays/out-of-pocket (Deductibles, especially if in a high deductible plan)',
  },
  { Owner: 'Self', Category: 'Health Medicle', Description: 'Gym / Health club dues' },
  { Owner: 'Self', Category: 'Health Medicle', Description: 'Med spa treatments' },
  { Owner: 'Self', Category: 'Health Medicle', Description: 'Medical Insurance Premiums' },
  { Owner: 'Self', Category: 'Health Medicle', Description: 'Over-the-counter drugs' },
  { Owner: 'Self', Category: 'Health Medicle', Description: 'Prescriptions' },
  { Owner: 'Self', Category: 'Health Medicle', Description: 'Procedures not covered by insurance (Elective or Cosmetic)' },
  { Owner: 'Self', Category: 'Health Medicle', Description: 'Vitamins' },
  { Owner: 'Self', Category: 'Health Medicle', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Health Medicle', Description: 'Enter' },
  { Owner: 'Self', Category: 'Other Insurance', Description: 'Collectables Insurance' },
  { Owner: 'Self', Category: 'Other Insurance', Description: 'Life Insurance' },
  { Owner: 'Self', Category: 'Other Insurance', Description: 'Personal Articles Insurance' },
  { Owner: 'Self', Category: 'Other Insurance', Description: "Renter's Insurance" },
  { Owner: 'Self', Category: 'Other Insurance', Description: 'Trust? Do you have one? 1x fee' },
  { Owner: 'Self', Category: 'Other Insurance', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Other Insurance', Description: 'Enter' },
  { Owner: 'Joint', Category: 'Other Insurance', Description: 'Enter' },
  { Owner: 'Self', Category: 'Other Insurance', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Other Insurance', Description: 'Enter' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Birthday Gifts' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Cell/Telephone' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Christmas Gifts' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Clothing subscriptions (Stitch Fix)' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Clothing, shoes & purses' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Dry Cleaning' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Furniture' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Gifts' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Hobby expenses' },
  {
    Owner: 'Self',
    Category: 'Household, Personal Care & Gifts',
    Description: 'Household Items (kitchenware, appliances, cookware, home décor etc.)',
  },
  {
    Owner: 'Self',
    Category: 'Household, Personal Care & Gifts',
    Description: "Income Tax Payment Due (Consider making add'l tax withholdings to avoid/minimize a tax bill)",
  },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Jewelry' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Make-up' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Misc. Allowance' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Office Supplies' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Salon/barber' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Spa Treatments' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Valentines Day Gift(s)' },
  { Owner: 'Self', Category: 'Household, Personal Care & Gifts', Description: 'Enter' },
  { Owner: 'Self', Category: 'Dues/Subscriptions', Description: 'Books' },
  { Owner: 'Self', Category: 'Dues/Subscriptions', Description: 'Game Apps' },
  { Owner: 'Self', Category: 'Dues/Subscriptions', Description: 'Magazines & Newspapers' },
  { Owner: 'Self', Category: 'Dues/Subscriptions', Description: 'Other Apps' },
  { Owner: 'Self', Category: 'Dues/Subscriptions', Description: 'Other Monthly Subscription Services' },
  { Owner: 'Self', Category: 'Dues/Subscriptions', Description: 'Professional Dues' },
  { Owner: 'Self', Category: 'Dues/Subscriptions', Description: 'Union Dues' },
  { Owner: 'Self', Category: 'Dues/Subscriptions', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Dues/Subscriptions', Description: 'Enter' },
  { Owner: 'Self', Category: 'Recreation', Description: 'Boat Payment' },
  { Owner: 'Self', Category: 'Recreation', Description: 'Gas /fuel' },
  { Owner: 'Self', Category: 'Recreation', Description: 'Golf Equipment (Gear, balls, etc.)' },
  { Owner: 'Self', Category: 'Recreation', Description: 'Golfing Tee Fees' },
  { Owner: 'Self', Category: 'Recreation', Description: 'Jetski Payment' },
  { Owner: 'Self', Category: 'Recreation', Description: 'Launch Fees' },
  { Owner: 'Self', Category: 'Recreation', Description: 'Maintenance/Repairs' },
  { Owner: 'Self', Category: 'Recreation', Description: 'Recreational Vehicle' },
  { Owner: 'Self', Category: 'Recreation', Description: 'Insurance: Boat, Jetski, Recreational Vehicle, etc.' },
  { Owner: 'Self', Category: 'Recreation', Description: 'Storage fees' },
  { Owner: 'Self', Category: 'Recreation', Description: 'Trip Expenses (Food, gas)' },
  { Owner: 'Self', Category: 'Recreation', Description: 'Wash/Detailing Service' },
  { Owner: 'Self', Category: 'Recreation', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Recreation', Description: 'Enter' },
  { Owner: 'Joint', Category: 'Recreation', Description: 'Enter' },
  { Owner: 'Self', Category: 'Recreation', Description: 'Enter' },
  { Owner: 'Partner', Category: 'Recreation', Description: 'Enter' },
  { Owner: 'Self', Category: 'Vacations', Description: 'Vacation #1' },
  { Owner: 'Self', Category: 'Vacations', Description: 'Vacation #2' },
  { Owner: 'Self', Category: 'Vacations', Description: 'Vacation #3' },
  { Owner: 'Self', Category: 'Vacations', Description: 'Weekend getaway #1' },
  { Owner: 'Self', Category: 'Vacations', Description: 'Weekend getaway #2' },
  { Owner: 'Self', Category: 'Vacations', Description: 'Weekend getaway #3' },
  { Owner: 'Self', Category: 'Vacations', Description: 'Weekend getaway #4' },
  { Owner: 'Self', Category: 'Vacations', Description: 'Weekend getaway #5' },
  { Owner: 'Self', Category: 'Vacations', Description: 'Weekend getaway #6' },
  { Owner: 'Self', Category: 'Rental Property', Description: 'Gardener - Rental Property' },
  { Owner: 'Self', Category: 'Rental Property', Description: 'HO Insurance - Rental Property' },
  { Owner: 'Self', Category: 'Rental Property', Description: 'Home Improvements - Rental Property' },
  { Owner: 'Self', Category: 'Rental Property', Description: 'Home Repairs - Rental Property' },
  { Owner: 'Self', Category: 'Rental Property', Description: 'Home Security - Rental Property' },
  { Owner: 'Self', Category: 'Rental Property', Description: 'Homeowner Dues #1 - Rental Property' },
  { Owner: 'Self', Category: 'Rental Property', Description: 'Homeowner Dues #2 - Rental Property' },
  { Owner: 'Self', Category: 'Rental Property', Description: 'Housecleaning service - Rental Property' },
  { Owner: 'Self', Category: 'Rental Property', Description: 'Mortgage Payment - Rental Property' },
  { Owner: 'Self', Category: 'Rental Property', Description: 'Pool Service - Rental Property' },
  { Owner: 'Self', Category: 'Rental Property', Description: 'Property Taxes - Rental Property' },
  { Owner: 'Self', Category: 'Rental Property', Description: 'Enter - Rental Property' },
  { Owner: 'Partner', Category: 'Rental Property', Description: 'Enter - Rental Property' },
  { Owner: 'Joint', Category: 'Rental Property', Description: 'Enter - Rental Property' },
  { Owner: 'Self', Category: 'Rental Property', Description: 'Enter - Rental Property' },
  { Owner: 'Partner', Category: 'Rental Property', Description: 'Enter - Rental Property' },
];
